### PR TITLE
#73, Typo

### PR DESCRIPTION
**Pull request by andreas-roehler**

### CODE REVIEW

**Comment by davidshepherd7** [comment]
Hi, thanks for this :slightly_smiling_face:. 

I think you accidentally pushed an extra commit (c48c9e7) to this PR. The typo fix is good to merge but I don't think that the fix for `==` in haskell will work. Have a look at the tests on partially evaluated operators in `features/haskell.feature` to see why (they are for `+`, but the same things apply to `==`).

**Comment by andreas-roehler** [comment]
Hi David, reflecting things a little bit further, being confident to get things done based on the presented approach. It should not take much time. Maybe we can co-author the new thing?

**Comment by andreas-roehler** [comment]
BTW when saying "new pull request" github adds it to the old-one. Didn't see that before.

**Comment by davidshepherd7** [comment]
I've done the typo fix manually so I'll this PR since the newer commits are unrelated.

As I said in the other issue I'm not currently interested in doing a major refactoring, let alone a rewrite. If you do want to do a rewrite you're welcome to start a new project for it and take any bits of code you like from electric-operator (I'd recommend reusing the tests if you want to reach feature parity). I will warn you that it's probably quite a bit more complex than your current code will be able to deal with. 

Good luck! :slightly_smiling_face:

**Pull request closed without merging**
