### PR TITLE
Improve support for Ruby

### PR DESCRIPTION
**Pull request by AjaiKN**

### CODE REVIEW

**Comment by davidshepherd7** [comment]
Looks nice!

Could you have a go at adding a test for `|` and maybe * and **? But if you can't get it to work then we can merge anyway and I'll do it some time later.

**Comment by AjaiKN** [comment]
Hmm, I hadn't realized that [`erts` files](https://www.gnu.org/software/emacs/manual/html_node/ert/erts-files.html) were only introduced in 29.1, so the tests are failing in 27.2 and 28.2 right now. If you have any other ideas about a nice way to test it, that would be great. Or I guess I could make the `erts` tests conditional on the Emacs version.

**Comment by AjaiKN** [comment]
I guess doing the same thing manually in elisp wouldn't be too bad, so I can convert the `erts` files to plain elisp if you'd like the tests to continue supporting Emacs 27/28.

**Comment by davidshepherd7** [comment]
Oh huh, TIL about erts, that's interesting!

But actually I'm already using something else very similar: the ecukes code in the features/ directory. You can either migrate your tests to that or merge without the tests and I'll do it :)

**Comment by AjaiKN** [comment]
Ah, somehow I totally missed the features/ directory!

I'm actually not sure if I'll have the time in the near future, so merging it without the tests would be great. Thanks! (And I've copied the `erts` file [here](https://gist.github.com/AjaiKN/a4d07bb2b132fc7a7f63633c4f411754) in case you want to reference it when adding the tests.)

**Comment by davidshepherd7** [comment]
Thanks! 🙂

**Pull request merged**
